#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C
export TZ=UTC
umask 022

usage() {
    cat >&2 <<'USAGE'
Usage: scripts/build-release-bundle.sh VERSION ARCH BIN_DIR PROFILE_DIR [OUT_DIR]

Assemble checksummed Linux tar and Debian artifacts without network access.
ARCH is amd64 or arm64. BIN_DIR must contain executable nq, nqd,
nq-host-helper, nq-host-resource-helper, nq-operator-beta-helper, and
nq-synthetic-cache-result-helper release binaries. Each must execute its
machine-readable --build-info probe and report VERSION, production helper
isolation policy, and one recorded source commit (built with NQ_SOURCE_COMMIT
set to the same full commit id) shared by all six. PROFILE_DIR must contain
one or more descriptor JSON files
generated by the matching nq source revision; its failure-code vocabularies
must agree with both nq and nq-host-resource-helper. Python must provide JSON
Schema Draft 2020-12 support (`jsonschema`). OUT_DIR defaults to ./dist.
USAGE
    exit 2
}

[[ $# -ge 4 && $# -le 5 ]] || usage

version=$1
arch=$2
bin_dir=$3
profile_dir=$4
out_dir=${5:-dist}

case "$version" in
    *[!0-9A-Za-z.+:~-]*|'')
        echo "invalid Debian-compatible version: $version" >&2
        exit 2
        ;;
esac
case "$arch" in
    amd64|arm64) ;;
    *)
        echo "ARCH must be amd64 or arm64" >&2
        exit 2
        ;;
esac

root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
bin_dir=$(cd -- "$bin_dir" && pwd -P)
profile_dir=$(cd -- "$profile_dir" && pwd -P)
mkdir -p -- "$out_dir"
out_dir=$(cd -- "$out_dir" && pwd -P)

for tool in dpkg-deb find flock gzip install md5sum mv python3 readelf sed sha256sum sort tar unlink; do
    command -v "$tool" >/dev/null 2>&1 || {
        echo "required local tool is missing: $tool" >&2
        exit 1
    }
done

# Serialize the complete validation/build/publication transaction on the
# already-open output-directory inode. The descriptor lock is released by the
# kernel on normal exit or process death and leaves no stale lock file.
exec 9<"$out_dir"
flock -n 9 || {
    echo "another release assembly owns $out_dir" >&2
    exit 1
}
# Every package-owned executable. Each helper serves at least one cataloged
# profile; the payload allowlist (packaging/tarball/MANIFEST.files) and the
# outside-in verifier (scripts/verify_release_payload.py) enumerate the same set.
binaries=(
    nq
    nqd
    nq-host-helper
    nq-host-resource-helper
    nq-operator-beta-helper
    nq-synthetic-cache-result-helper
)
for binary in "${binaries[@]}"; do
    [[ -f "$bin_dir/$binary" && -x "$bin_dir/$binary" ]] || {
        echo "missing executable $bin_dir/$binary" >&2
        exit 1
    }
done

expected_machine=''
case "$arch" in
    amd64) expected_machine='Advanced Micro Devices X86-64' ;;
    arm64) expected_machine='AArch64' ;;
esac
for binary in "${binaries[@]}"; do
    machine=$(readelf -h "$bin_dir/$binary" | sed -n 's/^[[:space:]]*Machine:[[:space:]]*//p')
    if [[ "$machine" != "$expected_machine" ]]; then
        echo "$bin_dir/$binary is $machine, not $arch ($expected_machine)" >&2
        exit 1
    fi
done

binary_paths=()
for binary in "${binaries[@]}"; do
    binary_paths+=("$bin_dir/$binary")
done
# The probe script prints the one source commit shared by every binary; the
# assembler records it in its final report so the release output names the
# source revision the cohort was built from.
source_commit=$(python3 - "$version" "${binary_paths[@]}" <<'PY'
import json
import os
import pathlib
import re
import subprocess
import sys


def strict_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key {key!r}")
        result[key] = value
    return result


requested_version = sys.argv[1]
# Each component name must equal its installed binary name; the shell passes
# the paths in this order.
components = (
    "nq",
    "nqd",
    "nq-host-helper",
    "nq-host-resource-helper",
    "nq-operator-beta-helper",
    "nq-synthetic-cache-result-helper",
)
expected_keys = {
    "schema",
    "component",
    "version",
    "debug_assertions",
    "helper_isolation_policy",
    "source_commit",
}
SOURCE_COMMIT = re.compile(r"^[0-9a-f]{40}$")
cohort_commit = None
cohort_witness = None
environment = os.environ.copy()
environment["NQ_CONFIG"] = "/nonexistent/nq-build-probe-must-not-load-config.toml"
for component, argument in zip(components, sys.argv[2:], strict=True):
    path = pathlib.Path(argument)
    try:
        completed = subprocess.run(
            [path, "--build-info"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
            timeout=5,
            env=environment,
        )
    except (OSError, subprocess.SubprocessError) as error:
        raise SystemExit(f"cannot execute build-policy probe for {path}: {error}") from error
    if completed.returncode != 0:
        diagnostic = completed.stderr.decode("utf-8", errors="replace").strip()
        raise SystemExit(
            f"build-policy probe for {path} exited {completed.returncode}: {diagnostic}"
        )
    if completed.stderr:
        raise SystemExit(f"build-policy probe for {path} emitted unexpected stderr")
    try:
        text = completed.stdout.decode("utf-8")
        if text.count("\n") != 1 or not text.endswith("\n"):
            raise ValueError("probe must emit exactly one newline-terminated JSON document")
        value = json.loads(text, object_pairs_hook=strict_object)
        if not isinstance(value, dict) or set(value) != expected_keys:
            raise ValueError("probe has missing or unknown fields")
        if value["schema"] != "nq.build_info.v2":
            raise ValueError("wrong build-info schema")
        if value["component"] != component:
            raise ValueError(
                f"component is {value['component']!r}, expected {component!r}"
            )
        if value["version"] != requested_version:
            raise ValueError(
                f"version is {value['version']!r}, requested {requested_version!r}"
            )
        if value["debug_assertions"] is not False:
            raise ValueError("debug assertions are enabled; build every binary with --release")
        if value["helper_isolation_policy"] != "production_separate_identity_required":
            raise ValueError("production separate-identity isolation policy is not compiled in")
        commit = value["source_commit"]
        if not isinstance(commit, str) or not SOURCE_COMMIT.fullmatch(commit):
            raise ValueError(
                f"source_commit is {commit!r}, not a full lowercase git commit id; "
                "build every release binary with NQ_SOURCE_COMMIT set"
            )
        if cohort_commit is None:
            cohort_commit = commit
            cohort_witness = component
        elif commit != cohort_commit:
            raise ValueError(
                f"source_commit {commit} differs from {cohort_witness}'s {cohort_commit}; "
                "release binaries must come from one source commit"
            )
    except (UnicodeError, ValueError, json.JSONDecodeError) as error:
        raise SystemExit(f"invalid build-policy probe from {path}: {error}") from error
print(cohort_commit)
PY
)
[[ "$source_commit" =~ ^[0-9a-f]{40}$ ]] || {
    echo "build-policy probe did not establish one source commit" >&2
    exit 1
}

mapfile -d '' descriptors < <(
    find "$profile_dir" -maxdepth 1 -type f -name '*.json' \
        ! -name 'manifest.json' ! -name 'failure-codes.json' -print0 | sort -z
)
if [[ ${#descriptors[@]} -eq 0 ]]; then
    echo "PROFILE_DIR contains no descriptor JSON files" >&2
    exit 1
fi
for descriptor in "${descriptors[@]}"; do
    name=$(basename -- "$descriptor")
    [[ "$name" =~ ^[A-Za-z0-9._-]+\.json$ && ! -L "$descriptor" ]] || {
        echo "unsafe descriptor path: $descriptor" >&2
        exit 1
    }
done
[[ -f "$profile_dir/manifest.json" && ! -L "$profile_dir/manifest.json" ]] || {
    echo "PROFILE_DIR is missing a regular manifest.json" >&2
    exit 1
}
[[ -f "$profile_dir/failure-codes.json" && ! -L "$profile_dir/failure-codes.json" ]] || {
    echo "PROFILE_DIR is missing a regular failure-codes.json" >&2
    exit 1
}
# The catalog must agree with the packaged nq and with the helper that serves
# the host-resource profiles; a helper whose failure-code vocabularies differ
# from nq's is refused here, before any staging.
python3 -B "$root/profiles/verify_catalog.py" \
    --catalog-dir "$profile_dir" \
    --helper "$bin_dir/nq-host-resource-helper" "$bin_dir/nq"
python3 -B "$root/scripts/verify_protocol_assets.py" \
    "$root/protocol" "$bin_dir/nq" "$version"
python3 - <<'PY'
try:
    from jsonschema import Draft202012Validator, FormatChecker, RefResolver  # noqa: F401
except (ImportError, AttributeError) as error:
    raise SystemExit(
        "required Python JSON Schema Draft 2020-12 support is unavailable"
    ) from error
PY
python3 -B "$root/system-contract/verify_assets.py" \
    --profile-catalog "$profile_dir/manifest.json"
python3 -B "$root/diagnostic-contract/verify_assets.py" \
    --source-vectors "$root/audit/nq-nightshift-stage6-foundation/vectors"
python3 -B "$root/diagnostic-contract-v2/verify_assets.py"
python3 - "${descriptors[@]}" <<'PY'
import json
import pathlib
import sys


def strict_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key {key!r}")
        result[key] = value
    return result


identities = set()
for argument in sys.argv[1:]:
    path = pathlib.Path(argument)
    try:
        value = json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=strict_object)
        if not isinstance(value, dict) or value.get("schema") != "nq.profile_descriptor.v1":
            raise ValueError("wrong or absent profile descriptor schema")
        profile = value.get("profile")
        if not isinstance(profile, dict):
            raise ValueError("profile identity is not an object")
        profile_id = profile.get("id")
        version = profile.get("version")
        if not isinstance(profile_id, str) or not profile_id:
            raise ValueError("profile id is absent")
        if isinstance(version, bool) or not isinstance(version, int) or version <= 0:
            raise ValueError("profile version is not a positive integer")
        identity = (profile_id, version)
        if identity in identities:
            raise ValueError(f"duplicate profile identity {profile_id} v{version}")
        identities.add(identity)
    except (OSError, UnicodeError, ValueError, json.JSONDecodeError) as error:
        raise SystemExit(f"invalid descriptor {path}: {error}") from error
PY

publish=''
work=''
cleanup() {
    if [[ -n "$publish" ]]; then
        rm -rf -- "$publish"
    fi
}
trap cleanup EXIT HUP INT TERM
# Build-time names are created only below this hidden directory on the same
# filesystem as OUT_DIR. Failure before publication leaves only uncommitted
# hidden scratch. Failure during publication may expose complete atomically
# renamed files, never partially written files; the absent bundle marker keeps
# that set uncommitted.
publish=$(mktemp -d "$out_dir/.nq-release-publish.XXXXXXXX")
work="$publish/.work"
mkdir -m 0700 -- "$work"

package="nq-ng-${version}-linux-${arch}"
stage="$work/$package"

install -Dm0755 "$bin_dir/nq" "$stage/bin/nq"
install -Dm0755 "$bin_dir/nqd" "$stage/bin/nqd"
install -Dm0755 "$bin_dir/nq-host-helper" \
    "$stage/lib/nq/helpers/nq-host-helper"
install -Dm0755 "$bin_dir/nq-host-resource-helper" \
    "$stage/lib/nq/helpers/nq-host-resource-helper"
install -Dm0755 "$bin_dir/nq-operator-beta-helper" \
    "$stage/lib/nq/helpers/nq-operator-beta-helper"
install -Dm0755 "$bin_dir/nq-synthetic-cache-result-helper" \
    "$stage/lib/nq/helpers/nq-synthetic-cache-result-helper"
install -Dm0755 \
    "$root/helpers/python-conformance/nq_conformance_helper.py" \
    "$stage/lib/nq/helpers/nq_conformance_helper.py"
install -Dm0644 "$root/packaging/systemd/nqd.service" \
    "$stage/lib/systemd/system/nqd.service"
install -Dm0644 "$root/packaging/systemd/nq.sysusers" \
    "$stage/lib/sysusers.d/nq.conf"
install -Dm0644 "$root/packaging/systemd/nq.tmpfiles" \
    "$stage/lib/tmpfiles.d/nq.conf"
install -Dm0644 "$root/docs/OPERATIONS.md" \
    "$stage/share/doc/nq-ng/OPERATIONS.md"
install -Dm0644 "$root/README.md" "$stage/share/doc/nq-ng/README.md"
install -Dm0644 "$root/LICENSE" "$stage/share/doc/nq-ng/LICENSE"
install -Dm0644 "$root/docs/PLAN.md" \
    "$stage/share/doc/nq-ng/docs/PLAN.md"
install -Dm0644 "$root/docs/DEVELOPMENT.md" \
    "$stage/share/doc/nq-ng/docs/DEVELOPMENT.md"
install -Dm0644 "$root/docs/IMPLEMENTATION_STATUS.md" \
    "$stage/share/doc/nq-ng/docs/IMPLEMENTATION_STATUS.md"
install -Dm0644 "$root/docs/PORTER_NETBOX_ADDENDUM.md" \
    "$stage/share/doc/nq-ng/docs/PORTER_NETBOX_ADDENDUM.md"
install -Dm0644 "$root/packaging/debian/copyright" \
    "$stage/share/doc/nq-ng/copyright"
install -Dm0644 "$root/examples/nq.toml" \
    "$stage/share/doc/nq-ng/examples/nq.toml"
install -Dm0644 "$root/examples/nq-host.toml" \
    "$stage/share/doc/nq-ng/examples/nq-host.toml"

for descriptor in "${descriptors[@]}"; do
    install -Dm0644 "$descriptor" "$stage/share/nq/profiles/$(basename -- "$descriptor")"
done
install -Dm0644 "$profile_dir/manifest.json" \
    "$stage/share/nq/profiles/manifest.json"
install -Dm0644 "$profile_dir/failure-codes.json" \
    "$stage/share/nq/profiles/failure-codes.json"
install -Dm0644 "$root/protocol/README.md" \
    "$stage/share/nq/protocol/README.md"
install -Dm0644 "$root/system-contract/manifest.json" \
    "$stage/share/nq/system-contract/manifest.json"
install -Dm0644 "$root/diagnostic-contract/README.md" \
    "$stage/share/nq/diagnostic-contract/README.md"
install -Dm0644 "$root/diagnostic-contract/manifest.json" \
    "$stage/share/nq/diagnostic-contract/manifest.json"
install -Dm0644 "$root/diagnostic-contract-v2/README.md" \
    "$stage/share/nq/diagnostic-contract-v2/README.md"
install -Dm0644 "$root/diagnostic-contract-v2/manifest.json" \
    "$stage/share/nq/diagnostic-contract-v2/manifest.json"

while IFS= read -r -d '' source; do
    relative=${source#"$root/protocol/"}
    install -Dm0644 "$source" "$stage/share/nq/protocol/$relative"
done < <(
    find "$root/protocol/schemas" "$root/protocol/fixtures" \
        -type f \( -name '*.json' -o -name '*.ndjson' \) -print0 \
        | sort -z
)

while IFS= read -r -d '' source; do
    relative=${source#"$root/system-contract/"}
    install -Dm0644 "$source" "$stage/share/nq/system-contract/$relative"
done < <(
    find "$root/system-contract/schemas" "$root/system-contract/fixtures/valid" \
        -type f -name '*.json' -print0 | sort -z
)

while IFS= read -r -d '' source; do
    relative=${source#"$root/diagnostic-contract/"}
    install -Dm0644 "$source" "$stage/share/nq/diagnostic-contract/$relative"
done < <(
    find "$root/diagnostic-contract/schemas" \
        "$root/diagnostic-contract/fixtures/valid" \
        "$root/diagnostic-contract/fixtures/hostile" \
        -type f -name '*.json' -print0 | sort -z
)

while IFS= read -r -d '' source; do
    relative=${source#"$root/diagnostic-contract-v2/"}
    install -Dm0644 "$source" "$stage/share/nq/diagnostic-contract-v2/$relative"
done < <(
    find "$root/diagnostic-contract-v2/schemas" \
        "$root/diagnostic-contract-v2/fixtures/valid" \
        "$root/diagnostic-contract-v2/fixtures/hostile" \
        -type f -name '*.json' -print0 | sort -z
)

# Re-run every asset/catalog verifier against the immutable staged copies.
# Source files changing or being left partial after the earlier input checks
# cannot turn into an unverified release payload.
python3 -B "$root/profiles/verify_catalog.py" \
    --catalog-dir "$stage/share/nq/profiles" \
    --helper "$stage/lib/nq/helpers/nq-host-resource-helper" "$stage/bin/nq"
python3 -B "$root/scripts/verify_protocol_assets.py" \
    "$stage/share/nq/protocol" "$stage/bin/nq" "$version"
python3 -B "$root/system-contract/verify_assets.py" \
    --asset-root "$stage/share/nq/system-contract" \
    --profile-catalog "$stage/share/nq/profiles/manifest.json"
python3 -B "$root/diagnostic-contract/verify_assets.py" \
    --asset-root "$stage/share/nq/diagnostic-contract" \
    --source-vectors "$root/audit/nq-nightshift-stage6-foundation/vectors"
python3 -B "$root/diagnostic-contract-v2/verify_assets.py" \
    --asset-root "$stage/share/nq/diagnostic-contract-v2"

(
    cd -- "$stage"
    find . -type f ! -path './share/nq/MANIFEST.sha256' -print0 \
        | sort -z \
        | xargs -0 sha256sum > share/nq/MANIFEST.sha256
)

descriptor_names=()
for descriptor in "${descriptors[@]}"; do
    descriptor_names+=("$(basename -- "$descriptor")")
done
python3 -B "$root/scripts/verify_release_payload.py" \
    "$stage" "${descriptor_names[@]}"

# A fixed epoch makes repeated assembly byte-for-byte stable when the inputs
# are stable. Release automation may set SOURCE_DATE_EPOCH to a commit time.
epoch=${SOURCE_DATE_EPOCH:-0}
[[ "$epoch" =~ ^[0-9]+$ ]] || {
    echo "SOURCE_DATE_EPOCH must be an unsigned integer" >&2
    exit 2
}
find "$stage" -exec touch -h -d "@$epoch" {} +

tar_name="$package.tar.gz"
tarball_staged="$publish/$tar_name"
tarball="$out_dir/$tar_name"
(
    cd -- "$work"
    tar --sort=name --mtime="@$epoch" --owner=0 --group=0 --numeric-owner \
        --format=ustar -cf - "$package" | gzip -n -9 > "$tarball_staged"
)

debroot="$work/debroot"
mkdir -p -- "$debroot/usr" "$debroot/DEBIAN"
cp -a -- "$stage/." "$debroot/usr/"
sed -e "s/@VERSION@/$version/g" -e "s/@ARCH@/$arch/g" \
    "$root/packaging/debian/control.in" > "$debroot/DEBIAN/control"
install -m0755 "$root/packaging/debian/postinst" "$debroot/DEBIAN/postinst"
install -m0755 "$root/packaging/debian/prerm" "$debroot/DEBIAN/prerm"
install -m0755 "$root/packaging/debian/postrm" "$debroot/DEBIAN/postrm"
(
    cd -- "$debroot"
    find usr -type f -print0 | sort -z | xargs -0 md5sum > DEBIAN/md5sums
)
find "$debroot" -exec touch -h -d "@$epoch" {} +

deb_name="nq-ng_${version}_${arch}.deb"
deb_staged="$publish/$deb_name"
deb="$out_dir/$deb_name"
dpkg-deb --root-owner-group --build "$debroot" "$deb_staged" >/dev/null

(
    cd -- "$publish"
    sha256sum "$tar_name" > "$tar_name.sha256"
    sha256sum "$deb_name" > "$deb_name.sha256"
    sha256sum "$tar_name" "$deb_name" > SHA256SUMS
    sha256sum --check SHA256SUMS >/dev/null
)

# Flush complete staged files before publishing their names. Artifact and
# per-artifact checksum renames happen first; SHA256SUMS is the commit marker
# and is renamed only after the directory containing those names is durable.
python3 - "$publish" <<'PY'
import os
import pathlib
import sys

directory = pathlib.Path(sys.argv[1])
for path in directory.iterdir():
    descriptor = os.open(path, os.O_RDONLY)
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)
descriptor = os.open(directory, os.O_RDONLY | os.O_DIRECTORY)
try:
    os.fsync(descriptor)
finally:
    os.close(descriptor)
PY

# Invalidate any previously committed bundle before replacing its members.
# Without this step a crash during rebuild could leave an old marker next to a
# mixture of old and new public names. Its digests would normally fail, but its
# mere presence would no longer be an unambiguous commit signal.
commit_marker="$out_dir/SHA256SUMS"
if [[ -e "$commit_marker" || -L "$commit_marker" ]]; then
    [[ -f "$commit_marker" && ! -L "$commit_marker" ]] || {
        echo "existing bundle marker is not a regular non-symlink file: $commit_marker" >&2
        exit 1
    }
    unlink -- "$commit_marker"
    python3 - "$out_dir" <<'PY'
import os
import sys

descriptor = os.open(sys.argv[1], os.O_RDONLY | os.O_DIRECTORY)
try:
    os.fsync(descriptor)
finally:
    os.close(descriptor)
PY
fi

for name in "$tar_name" "$tar_name.sha256" "$deb_name" "$deb_name.sha256"; do
    mv -fT -- "$publish/$name" "$out_dir/$name"
done
python3 - "$out_dir" <<'PY'
import os
import sys

descriptor = os.open(sys.argv[1], os.O_RDONLY | os.O_DIRECTORY)
try:
    os.fsync(descriptor)
finally:
    os.close(descriptor)
PY
mv -fT -- "$publish/SHA256SUMS" "$out_dir/SHA256SUMS"
python3 - "$out_dir" <<'PY'
import os
import sys

descriptor = os.open(sys.argv[1], os.O_RDONLY | os.O_DIRECTORY)
try:
    os.fsync(descriptor)
finally:
    os.close(descriptor)
PY

printf 'created %s\ncreated %s\nchecksums %s\nsource_commit %s\n' \
    "$tarball" "$deb" "$out_dir/SHA256SUMS" "$source_commit"
