[package]
name = "nq-store-gen4-default-surface"
version = "0.0.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
nq-host-role-runtime = { path = "../../../../nq-host-role-runtime" }
nq-runtime-dependency-authority = { path = "../../../../nq-runtime-dependency-authority" }
nq-store = { path = "../../../../nq-store" }
